name: Docker

on:
  push:
    paths:
      - "apps/api/**"
      - "apps/slack/**"
      - ".github/workflows/docker.yaml"
    branches:
      - main
    tags:
      - "*"

permissions:
  contents: read
  packages: write

env:
  PROJECT_NAME: whitestone-capital

jobs:
  ghcr:
    strategy:
      matrix:
        app:
          - api

    name: Publish ${{ matrix.app }} Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Login ghcr.io
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Docker Metadata for ${{ matrix.app }}
        uses: docker/metadata-action@c299e40c65443455700f0fdfc63efafe5b349051 # v5
        id: meta
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/${{ env.PROJECT_NAME }}_${{ matrix.app }}
          tags: |
            type=raw,value=latest,enable=${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
            type=sha,enable=${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
            type=ref,event=tag,enable=${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') }}

      - name: Build and Push ${{ matrix.app }} Docker Image
        uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8 # v6
        with:
          context: ./apps/${{ matrix.app }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
